name: 'Hello World'
description: 'Prints a greeting for a supplied name to the console.'

inputs:
  who-to-greet:
    description: 'The name of the person to greet.'
    required: true
    default: ''

runs:
  using: 'node20'
  main: 'index.js'