name: Test
on: pull_request

permissions:
  id-token: write
  contents: read

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Initialise
        run: echo "Hello World!"

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-skip-session-tagging: true
          role-to-assume: arn:aws:iam::312279720510:role/github-actions-test-workflows
          aws-region: ap-southeast-2